implemented file reading fucntionality
AnaLanda/jv-amazon-reviews pull request #1
Opened 2020-11-09 11:34 UTC by AnaLanda

2020-11-09 15:58 UTC, MaliukDaria commented on pom.xml
> +    <packaging>war</packaging>
нам нужен war архив?

2020-11-10 10:37 UTC, KseniiaMakarova requested changes

2020-11-10 10:37 UTC, KseniiaMakarova commented on pom.xml
> +    <packaging>war</packaging>
I agree, this may be redundant

2020-11-10 10:37 UTC, KseniiaMakarova commented on pom.xml
> +        </dependency>
this as well
everything we need is already included in spring-boot-starter-web

2020-11-10 10:37 UTC, KseniiaMakarova commented on pom.xml
> +                </plugin>
same

2020-11-10 10:37 UTC, KseniiaMakarova commented on pom.xml
> -                <artifactId>spring-boot-maven-plugin</artifactId>
try returning this plugin if you meet any issues

2020-11-10 10:37 UTC, KseniiaMakarova commented on src/main/java/com/amazon/reviews/ServletInitializer.java
> +public class ServletInitializer extends SpringBootServletInitializer {
I think this might be redundant as well

2020-11-10 10:37 UTC, KseniiaMakarova commented on src/test/java/com/amazon/reviews/impl/FileReaderServiceImplTest.java
> +
```suggestion
```

2020-11-10 10:37 UTC, KseniiaMakarova commented on src/test/java/com/amazon/reviews/impl/FileReaderServiceImplTest.java
> +        FileReaderService reader = new FileReaderServiceImpl();
you can make a field instead and initialise it once before all tests

2020-11-10 16:07 UTC, KseniiaMakarova requested changes

2020-11-10 16:07 UTC, KseniiaMakarova commented on src/main/java/com/amazon/reviews/service/impl/FileReaderServiceImpl.java
> +        try (Stream<String> stream = Files.lines(Paths.get(path))) {
I think we should better move this out from try-with-resources
and just use try-catch)

2020-11-10 16:07 UTC, KseniiaMakarova commented on src/test/java/com/amazon/reviews/impl/FileReaderServiceImplTest.java
> +    private static final FileReaderService reader = new FileReaderServiceImpl();
```suggestion
    private final FileReaderService reader = new FileReaderServiceImpl();
```

2020-11-11 08:11 UTC, KseniiaMakarova approved these changes

2020-11-11 09:39 UTC, merged